version: "3.7"

services:

  influxdb:
    container_name: omgind_influxdb
    image: "influxdb:2.0-alpine"
    restart: always
    env_file:
      - ${CONFIG_FILE}

#    environment:
#      DOCKER_INFLUXDB_INIT_USERNAME: omgind
#      DOCKER_INFLUXDB_INIT_PASSWORD: "12345678"
#      DOCKER_INFLUXDB_INIT_ORG: "omgind"
#      DOCKER_INFLUXDB_INIT_BUCKET: "omgind"
#      DOCKER_INFLUXDB_INIT_RETENTION: 1w
#      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 12345678

    volumes:
      - ${PROJECT_DIR}/data/influxdb:/var/lib/influxdb2
#      - ${PROJECT_DIR}/data/config/influx:/etc/influxdb2

    ports:
      - 8086:8086

    networks:
      - net

