version: "3.7"

services:

  core:
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    container_name: omgind_redis
    restart: always

    volumes:
      - ${VOLUME_DIR}/redis/data:/data
      - ${CONFIG_DIR}/redis/redis.conf:/etc/redis.conf

    command: ["redis-server", "/etc/redis.conf", "--requirepass", "$REDIS_PASSWORD"]
    env_file:
      - ${CONFIG_FILE}

    ports:
      - "16739:6739"

    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p $$REDIS_PORT -a $$REDIS_PASSWORD info"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

    networks:
      - net
