version: "3.7"

services:

  core:
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:12-alpine"
    container_name: omgind_pgsql
    privileged: true
    restart: always
    env_file:
      - ${CONFIG_FILE}
#    environment:
#      POSTGRES_USER: omgind
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_DB: omgind
#      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ${PROJECT_DIR}/data/pgsql:/var/lib/postgresql/data/pgdata

    ports:
      - 15432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - net


